const productData = [
    {
        id: 2,
        product_code: 'a11',
        product_name: 'p1',
        product_price: 10,
        merchantId: 6,
        createdAt: '2019-04-22T03: 40: 24.660Z',
        updatedAt: '2019-04-22T03: 40: 24.660Z',
        menus: [],
        merchant: {
            id: 6,
            limitations: {
                max_tax: 3,
                max_menu: 2,
                max_store: 2,
                max_table: 30,
                max_charge: 3,
                max_product: 50,
                max_employee: 10,
                max_toppping: 50,
            },
            merchant_name: 'Food HUnter',
            license: 'http: //ordo-koa.herokuapp.com/download/233113b4-2187-4d65-b0e2-a1fe0dd336f1',
            createdAt: '2019-04-12T03: 48: 20.709Z',
            updatedAt: '2019-04-12T03: 48: 24.974Z',
            link: {
                base: 'http: //ordo-koa.herokuapp.com/',
                path: 'postgres/product/',
                self: 6,
            },
        },
        toppings: [],
        link: {
            base: 'http: //ordo-koa.herokuapp.com/',
            path: 'postgres/product/',
            self: 2,
        },
    },
    {
        id: 5,
        product_code: 'A3',
        product_name: 'Fish',
        product_price: 20,
        merchantId: 6,
        createdAt: '2019-04-22T03: 42: 22.566Z',
        updatedAt: '2019-04-22T03: 42: 22.566Z',
        menus: [],
        merchant: {
            id: 6,
            limitations: {
                max_tax: 3,
                max_menu: 2,
                max_store: 2,
                max_table: 30,
                max_charge: 3,
                max_product: 50,
                max_employee: 10,
                max_toppping: 50,
            },
            merchant_name: 'Food HUnter',
            license: 'http: //ordo-koa.herokuapp.com/download/233113b4-2187-4d65-b0e2-a1fe0dd336f1',
            createdAt: '2019-04-12T03: 48: 20.709Z',
            updatedAt: '2019-04-12T03: 48: 24.974Z',
            link: {
                base: 'http: //ordo-koa.herokuapp.com/',
                path: 'postgres/product/',
                self: 6,
            },
        },
        toppings: [],
        link: {
            base: 'http: //ordo-koa.herokuapp.com/',
            path: 'postgres/product/',
            self: 5,
        },
    },
    {
        id: 6,
        product_code: 'A4',
        product_name: 'Chicken',
        product_price: 25,
        merchantId: 6,
        createdAt: '2019-04-22T03: 42: 36.322Z',
        updatedAt: '2019-04-22T03: 42: 36.322Z',
        menus: [],
        merchant: {
            id: 6,
            limitations: {
                max_tax: 3,
                max_menu: 2,
                max_store: 2,
                max_table: 30,
                max_charge: 3,
                max_product: 50,
                max_employee: 10,
                max_toppping: 50,
            },
            merchant_name: 'Food HUnter',
            license: 'http: //ordo-koa.herokuapp.com/download/233113b4-2187-4d65-b0e2-a1fe0dd336f1',
            createdAt: '2019-04-12T03: 48: 20.709Z',
            updatedAt: '2019-04-12T03: 48: 24.974Z',
            link: {
                base: 'http: //ordo-koa.herokuapp.com/',
                path: 'postgres/product/',
                self: 6,
            },
        },
        toppings: [],
        link: {
            base: 'http: //ordo-koa.herokuapp.com/',
            path: 'postgres/product/',
            self: 6,
        },
    },
    {
        id: 4,
        product_code: 'A2',
        product_name: 'product name',
        product_price: 20,
        merchantId: 6,
        createdAt: '2019-04-22T03: 42: 15.525Z',
        updatedAt: '2019-04-22T03: 42: 15.525Z',
        menus: [],
        merchant: {
            id: 6,
            limitations: {
                max_tax: 3,
                max_menu: 2,
                max_store: 2,
                max_table: 30,
                max_charge: 3,
                max_product: 50,
                max_employee: 10,
                max_toppping: 50,
            },
            merchant_name: 'Food HUnter',
            license: 'http: //ordo-koa.herokuapp.com/download/233113b4-2187-4d65-b0e2-a1fe0dd336f1',
            createdAt: '2019-04-12T03: 48: 20.709Z',
            updatedAt: '2019-04-12T03: 48: 24.974Z',
            link: {
                base: 'http: //ordo-koa.herokuapp.com/',
                path: 'postgres/product/',
                self: 6,
            },
        },
        toppings: [],
        link: {
            base: 'http: //ordo-koa.herokuapp.com/',
            path: 'postgres/product/',
            self: 4,
        },
    },
    {
        id: 3,
        product_code: 'A1',
        product_name: 'asdsakldj',
        product_price: 100,
        merchantId: 6,
        createdAt: '2019-04-22T03: 42: 00.034Z',
        updatedAt: '2019-04-22T03: 42: 00.034Z',
        menus: [],
        merchant: {
            id: 6,
            limitations: {
                max_tax: 3,
                max_menu: 2,
                max_store: 2,
                max_table: 30,
                max_charge: 3,
                max_product: 50,
                max_employee: 10,
                max_toppping: 50,
            },
            merchant_name: 'Food HUnter',
            license: 'http: //ordo-koa.herokuapp.com/download/233113b4-2187-4d65-b0e2-a1fe0dd336f1',
            createdAt: '2019-04-12T03: 48: 20.709Z',
            updatedAt: '2019-04-12T03: 48: 24.974Z',
            link: {
                base: 'http: //ordo-koa.herokuapp.com/',
                path: 'postgres/product/',
                self: 6,
            },
        },
        toppings: [],
        link: {
            base: 'http: //ordo-koa.herokuapp.com/',
            path: 'postgres/product/',
            self: 3,
        },
    },
];

export default productData;
